name: silvermaple
favicon: null
layout_spectrum: 1
typography_spectrum: 0.32992
title: Silver Maple - A Shady Place
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#37561d'
    - '#5e7821'
    - '#a58149'
    - '#bbbeac'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
