name: silvermaple
favicon: null
layout_spectrum: 0.75482
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#37561d'
    - '#5e7821'
    - '#a58149'
    - '#bbbeac'
  brandStrength: 0.6906811874359846
  lightness: 0.9077326736878604
  saturation: 0.5637611749116331
  rhythmicContrast: 0.6842369879595935
purpose: []
